Check env

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -7,6 +7,7 @@ ARG ENV
 
 RUN if [ "$ENV" = "production" ] ; then npm run build:production; fi
 RUN if [ "$ENV" = "acceptance" ] ; then npm run build:acceptance; fi
+RUN if [ "$ENV" = "" ] ; then echo 'invalid env';exit 1; fi
 
 FROM caddy:alpine
 WORKDIR /app/
